kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: "azure-sci-exporter-scrap"
      static_configs:
        - targets:
          - "azure-sci-exporter.azure-sci-exporter.svc.cluster.local:8000"
    - job_name: opencost
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: 
         - 'opencost.opencost:9003'
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system