version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/root/.kube/config
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"