kind: Config
preferences: {}
users:
  - name: user-name
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: kubelogin
        args:
          - get-token
          - --environment
          - AzurePublicCloud
          - --server-id
          - 6dae42f8-4368-4678-94ff-3960e28e3630
          - --client-id
          - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
          - --tenant-id
          - 16b3c013-d300-468d-ac64-7eda0820b6d3
