global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Self
  - job_name: "prometheus-server"
    static_configs:
      - targets:
          - "localhost:9090"

  # Python example
  - job_name: "ief-metrics-exporter"
    static_configs:
      - targets:
          - "ief_metrics_exporter:8000"